# Для начала работы заменить данные на свои.
# Затем зайти в настройки нужного проекта на странице -> https://ci.appveyor.com/project/
# Вкладка "General" и поставить галку на пункте: 
#                Skip branches without appveyor.yml
# После прокрутить страницу вниз - сохранить изменения
# Эта настройка для того чтоб ветка deploy не запускала заново весь цикл AppVeyor.

environment:
  access_token:
    secure: c/tnRC40qb/r3WFQ63iBsInAL15UlFR81E0Gc0332lhM06C8y0yT0IBo9vOkWyDE # Token GitHub API(personal access tokken)
    # Заменить на свой!!
    # Получить здесь -> https://github.com/settings/tokens
    # Далее в личном кабинете на сайте AppVeyor 
    # токен нужно зашифровать -> https://ci.appveyor.com/tools/encrypt 
    # И вставить в поле "secure:"
  email:
    secure: 3FrN4d/vOe5YI82rHbfneYECAhNWE2sx+IyGhYTOMA0= # email для подписи коммита,
    # Шифровать не обязательно, я шифровал там же где токен.

  name:
    secure: V7e5Ri2x9wywWs44eYFYyA== #   name - для того же.
    # Шифровать не обязательно, я шифровал.

  commit_message: b-v$(APPVEYOR_BUILD_VERSION)
  deploy_branch_name: deploy
  
image: Ubuntu2004 # образ для сборки

stack: node 14 # окружение


branches:
  only:
    - main # ветка git

cache: node_modules # кеширование

skip_tags: true

install:
  - npm install #  команда установки зависимостей

build_script:
  - npm run build # команда сборки

test_script:
  - npm run lint # && npm test  # скрипт тестирования

after_test:
  - git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - ps: git config --global user.email $($env:email)
  - ps: git config --global user.name $($env:name)
  - git fetch 
  - ps: git checkout $($env:deploy_branch_name)
  - ps: New-Item -Path . -Name ".version" -ItemType "file" -Value $($env:commit_message) -Force
  - git add .version
  - git add -f ./dist/*
  - git mv -f ./dist/* .
  - ps: git commit -m "Build - $($env:commit_message)"
  - ps: git push -u origin $($env:deploy_branch_name)
  
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: myproduct-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $($env:access_token) # your encrypted token from GitHub
  artifact: /.\*/          # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: main                # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
