environment:
  access_token:
    secure: m1zGMpElPHc3J+yo4jw/xs8qVOVDQ3pDfac9nNANIZnFGam1YMtzBwkppr7GStH2
  email:
    secure: wbiqfZ/8qu/fKl/93/gNKQ==
  name:
    secure: lhx+pnL9RyhNybnzRrKO9A==
  build_name: build-v$(APPVEYOR_BUILD_VERSION)
  
image: Ubuntu2004 # образ для сборки

stack: node 14 # окружение


branches:
  only:
    - main # ветка git
  except:
    - build

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build # команда сборки

test_script:
  - npm run lint # && npm test  # скрипт тестирования

after_test:
  - git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - ps: git config --global user.email $($env:email)
  - ps: git config --global user.name $($env:name)
  - ps: git checkout -b $($env:build_name)
  - git rm --cached -r .
  - git add -f dist 
  - ps: Move-Item -Path ./dist/* -Destination ./
  - ps: Remove-Item -Path dist
  - ps: git commit -m "build-$($env:build_name)"
  - ps: git push --set-upstream origin -b $($env:build_name)
  
